### ISSUE TITLE
Enabling OFDM Radar System Parameters block causes a NameError warning 

### ISSUE THREAD

**Issue by chrisjohgorman** [Yamakaja/gr-ofdmradar#3]
Hello,

This is pretty self explanatory.  I don't know if there are repercussions with failures because of this, but enabling the OFDM Radar System Parameters block causes the following warning for me in gnuradio.

I've looked around and can't tell where the error is.  I'm hoping that someone with more knowledge of the code can fix this or even if they can't if they can tell me whether or not this is benign.

Thanks in advance,

Chris

`[chris@descartes ~]$ gnuradio-companion 
<<< Welcome to GNU Radio Companion 3.10.7.0 >>>

Block paths:
        /home/chris/.grc_gnuradio
        /usr/local/share/gnuradio/grc/blocks

Loading: "/home/chris/hardy/gr-ofdmradar/examples/ofdmradar_test.grc"
>>> Done
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gnuradio/grc/gui/VariableEditor.py", line 194, in set_value
    value = str(block.evaluate(block.value))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gnuradio/grc/core/blocks/block.py", line 645, in evaluate
    return self.parent_flowgraph.evaluate(expr, self.namespace)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gnuradio/grc/core/FlowGraph.py", line 309, in evaluate
    return eval(expr, namespace, local_namespace)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'window' is not defined
[chris@descartes ~]$ `

**Comment by atom317** [comment]
There is an issue in the `ofdmradar_ofdmradar_params.block.yml` file within the project. It references the `window` module but fails to import the corresponding Python library. You need to import the `window` module in the `imports` section as follows:

```yaml
templates:
  imports: |-
    import ofdmradar
    from gnuradio.fft import window  # Import the window module
```

**Comment by chrisjohgorman** [comment]
Thank you @atom317.  I'll try a build with your recommended change.

Best regards,

Chris
